[colors]
draw_bold_text_with_bright_colors = false

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u001B[Z"
key = "Tab"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B-"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[colors.bright]
black = "0x636e7b"
blue = "0x6cb6ff"
cyan = "0x39c5cf"
green = "0x6bc46d"
magenta = "0xdcbdfb"
red = "0xff938a"
white = "0xcdd9e5"
yellow = "0xdaaa3f"

[colors.normal]
black = "0x545d68"
blue = "0x539bf5"
cyan = "0x39c5cf"
green = "0x57ab5a"
magenta = "0xb083f0"
red = "0xf47067"
white = "0xadbac7"
yellow = "0xc69026"

[colors.primary]
background = "0x22272e"
foreground = "0xadbac7"

[env]
TERM = "alacritty"

[font]
size = 20

[font.bold]
family = "Hack Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[font.offset]
x = 0
y = 0

[window]
option_as_alt = "Both"

[keyboard]
